import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/reset.css'
import '@/styles/globals.css'
import { Providers } from '@/app/providers'
import HeaderMain from '@/components/Layouts/HeaderMain'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <Providers>
        <body className={inter.className}>
          <HeaderMain />
          {children}
        </body>
      </Providers>
    </html>
  )
}
